// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/presentation/protobuf/schema.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_UP    Direction = 0
	Direction_DOWN  Direction = 1
	Direction_LEFT  Direction = 2
	Direction_RIGHT Direction = 3
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "UP",
		1: "DOWN",
		2: "LEFT",
		3: "RIGHT",
	}
	Direction_value = map[string]int32{
		"UP":    0,
		"DOWN":  1,
		"LEFT":  2,
		"RIGHT": 3,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_presentation_protobuf_schema_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_internal_presentation_protobuf_schema_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_internal_presentation_protobuf_schema_proto_rawDescGZIP(), []int{0}
}

type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_internal_presentation_protobuf_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Welcome) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Welcome) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Welcome) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Move struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Direction      Direction              `protobuf:"varint,2,opt,name=direction,proto3,enum=Direction" json:"direction,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,3,opt,name=sequenceNumber,proto3" json:"sequenceNumber,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_internal_presentation_protobuf_schema_proto_rawDescGZIP(), []int{1}
}

func (x *Move) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_UP
}

func (x *Move) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type Players struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*Players_Player      `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Players) Reset() {
	*x = Players{}
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Players) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Players) ProtoMessage() {}

func (x *Players) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Players.ProtoReflect.Descriptor instead.
func (*Players) Descriptor() ([]byte, []int) {
	return file_internal_presentation_protobuf_schema_proto_rawDescGZIP(), []int{2}
}

func (x *Players) GetPlayers() []*Players_Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *Players) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Disconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disconnect) Reset() {
	*x = Disconnect{}
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disconnect) ProtoMessage() {}

func (x *Disconnect) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disconnect.ProtoReflect.Descriptor instead.
func (*Disconnect) Descriptor() ([]byte, []int) {
	return file_internal_presentation_protobuf_schema_proto_rawDescGZIP(), []int{3}
}

func (x *Disconnect) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_internal_presentation_protobuf_schema_proto_rawDescGZIP(), []int{4}
}

func (x *Ping) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_internal_presentation_protobuf_schema_proto_rawDescGZIP(), []int{5}
}

func (x *Pong) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Join struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Join) Reset() {
	*x = Join{}
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Join) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Join) ProtoMessage() {}

func (x *Join) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Join.ProtoReflect.Descriptor instead.
func (*Join) Descriptor() ([]byte, []int) {
	return file_internal_presentation_protobuf_schema_proto_rawDescGZIP(), []int{6}
}

func (x *Join) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type Connect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connect) Reset() {
	*x = Connect{}
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connect) ProtoMessage() {}

func (x *Connect) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connect.ProtoReflect.Descriptor instead.
func (*Connect) Descriptor() ([]byte, []int) {
	return file_internal_presentation_protobuf_schema_proto_rawDescGZIP(), []int{7}
}

func (x *Connect) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Connect) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type Nicknames struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*Nicknames_Player    `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nicknames) Reset() {
	*x = Nicknames{}
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nicknames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nicknames) ProtoMessage() {}

func (x *Nicknames) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nicknames.ProtoReflect.Descriptor instead.
func (*Nicknames) Descriptor() ([]byte, []int) {
	return file_internal_presentation_protobuf_schema_proto_rawDescGZIP(), []int{8}
}

func (x *Nicknames) GetPlayers() []*Nicknames_Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type Players_Player struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       int32                  `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	X              int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y              int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,5,opt,name=sequenceNumber,proto3" json:"sequenceNumber,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Players_Player) Reset() {
	*x = Players_Player{}
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Players_Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Players_Player) ProtoMessage() {}

func (x *Players_Player) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Players_Player.ProtoReflect.Descriptor instead.
func (*Players_Player) Descriptor() ([]byte, []int) {
	return file_internal_presentation_protobuf_schema_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Players_Player) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Players_Player) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Players_Player) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Players_Player) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type Nicknames_Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nicknames_Player) Reset() {
	*x = Nicknames_Player{}
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nicknames_Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nicknames_Player) ProtoMessage() {}

func (x *Nicknames_Player) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_protobuf_schema_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nicknames_Player.ProtoReflect.Descriptor instead.
func (*Nicknames_Player) Descriptor() ([]byte, []int) {
	return file_internal_presentation_protobuf_schema_proto_rawDescGZIP(), []int{8, 0}
}

func (x *Nicknames_Player) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Nicknames_Player) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

var File_internal_presentation_protobuf_schema_proto protoreflect.FileDescriptor

const file_internal_presentation_protobuf_schema_proto_rawDesc = "" +
	"\n" +
	"+internal/presentation/protobuf/schema.proto\"A\n" +
	"\aWelcome\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\x05R\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"X\n" +
	"\x04Move\x12(\n" +
	"\tdirection\x18\x02 \x01(\x0e2\n" +
	".DirectionR\tdirection\x12&\n" +
	"\x0esequenceNumber\x18\x03 \x01(\x05R\x0esequenceNumber\"\xbc\x01\n" +
	"\aPlayers\x12)\n" +
	"\aplayers\x18\x01 \x03(\v2\x0f.Players.PlayerR\aplayers\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x1ah\n" +
	"\x06Player\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\x05R\bplayerId\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12&\n" +
	"\x0esequenceNumber\x18\x05 \x01(\x05R\x0esequenceNumber\"(\n" +
	"\n" +
	"Disconnect\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\x05R\bplayerId\"$\n" +
	"\x04Ping\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"$\n" +
	"\x04Pong\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\"\n" +
	"\x04Join\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\"A\n" +
	"\aConnect\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\x05R\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\"z\n" +
	"\tNicknames\x12+\n" +
	"\aplayers\x18\x01 \x03(\v2\x11.Nicknames.PlayerR\aplayers\x1a@\n" +
	"\x06Player\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\x05R\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname*2\n" +
	"\tDirection\x12\x06\n" +
	"\x02UP\x10\x00\x12\b\n" +
	"\x04DOWN\x10\x01\x12\b\n" +
	"\x04LEFT\x10\x02\x12\t\n" +
	"\x05RIGHT\x10\x03B-Z+chickenswarm/internal/presentation/protobufb\x06proto3"

var (
	file_internal_presentation_protobuf_schema_proto_rawDescOnce sync.Once
	file_internal_presentation_protobuf_schema_proto_rawDescData []byte
)

func file_internal_presentation_protobuf_schema_proto_rawDescGZIP() []byte {
	file_internal_presentation_protobuf_schema_proto_rawDescOnce.Do(func() {
		file_internal_presentation_protobuf_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_presentation_protobuf_schema_proto_rawDesc), len(file_internal_presentation_protobuf_schema_proto_rawDesc)))
	})
	return file_internal_presentation_protobuf_schema_proto_rawDescData
}

var file_internal_presentation_protobuf_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_presentation_protobuf_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_presentation_protobuf_schema_proto_goTypes = []any{
	(Direction)(0),           // 0: Direction
	(*Welcome)(nil),          // 1: Welcome
	(*Move)(nil),             // 2: Move
	(*Players)(nil),          // 3: Players
	(*Disconnect)(nil),       // 4: Disconnect
	(*Ping)(nil),             // 5: Ping
	(*Pong)(nil),             // 6: Pong
	(*Join)(nil),             // 7: Join
	(*Connect)(nil),          // 8: Connect
	(*Nicknames)(nil),        // 9: Nicknames
	(*Players_Player)(nil),   // 10: Players.Player
	(*Nicknames_Player)(nil), // 11: Nicknames.Player
}
var file_internal_presentation_protobuf_schema_proto_depIdxs = []int32{
	0,  // 0: Move.direction:type_name -> Direction
	10, // 1: Players.players:type_name -> Players.Player
	11, // 2: Nicknames.players:type_name -> Nicknames.Player
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_presentation_protobuf_schema_proto_init() }
func file_internal_presentation_protobuf_schema_proto_init() {
	if File_internal_presentation_protobuf_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_presentation_protobuf_schema_proto_rawDesc), len(file_internal_presentation_protobuf_schema_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_presentation_protobuf_schema_proto_goTypes,
		DependencyIndexes: file_internal_presentation_protobuf_schema_proto_depIdxs,
		EnumInfos:         file_internal_presentation_protobuf_schema_proto_enumTypes,
		MessageInfos:      file_internal_presentation_protobuf_schema_proto_msgTypes,
	}.Build()
	File_internal_presentation_protobuf_schema_proto = out.File
	file_internal_presentation_protobuf_schema_proto_goTypes = nil
	file_internal_presentation_protobuf_schema_proto_depIdxs = nil
}
